apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      nodeSelector:                    # ✅ Moved to pod spec level
        kubernetes.io/arch: arm64
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest-arm64
        args:
        - tunnel
        - --no-autoupdate
        - run
        - --token=$(TUNNEL_TOKEN)
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: tunnel-credentials
              key: token
        resources:                     # ✅ Moved inside container
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        # ✅ No health checks to avoid complexity
