apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest    # ✅ Specific stable version
        args:
        - tunnel
        - --no-autoupdate
        - run
        - --token=$(TUNNEL_TOKEN)
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: tunnel-credentials
              key: token
        # ✅ NO RESOURCE CONSTRAINTS - Allow unlimited resources
