apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}  # Avoid appending color here to prevent duplication
  labels:
    app: {{ .Values.appName | default "auth-service" }}
    color: {{ .Values.color }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.appName | default "auth-service" }}
      color: {{ .Values.color }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName | default "auth-service" }}
        color: {{ .Values.color }}
    spec:
      {{- if .Values.imagePullSecrets }}  # Add this block
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
      containers:
        - name: auth-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secret
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          # Add readiness/liveness probes if not present for better rollout detection
          readinessProbe:
            httpGet:
              path: /health  # Adjust to your app's health endpoint
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 10
