apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-network-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.appName }}
      color: {{ .Values.color }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - namespaceSelector: {}
      ports:
      - protocol: TCP
        port: {{ .Values.service.targetPort }}
  egress:
    # Allow DNS
    - to:
      - namespaceSelector: {}
      ports:
      - protocol: UDP
        port: 53
    # Allow HTTPS
    - to:
      - namespaceSelector: {}
      ports:
      - protocol: TCP
        port: 443
    # Allow PostgreSQL
    - to:
      - namespaceSelector: {}
      ports:
      - protocol: TCP
        port: 5432
    # Allow all to pods in same namespace
    - to:
      - podSelector: {}
