{{- if eq .Values.color "blue" }}
# Only create service on first (blue) deployment
# Service will be shared by both blue and green deployments
apiVersion: v1
kind: Service
metadata:
  name: auth-service  # Fixed name - NOT tied to release
  namespace: {{ .Release.Namespace }}
  labels:
    app: auth-service
  annotations:
    # Prevent Helm from claiming ownership
    helm.sh/resource-policy: keep
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  selector:
    app: auth-service
    color: {{ .Values.color }}  # Jenkins will patch this
{{- end }}
