apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}  # Shared service name for blue-green
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}  # LoadBalancer for MetalLB
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "auth-service.name" . }}
    color: {{ .Values.color | default "blue" }}  # Patched during blue-green switch
