{{- if not (lookup "v1" "Service" .Release.Namespace "auth-service") }}
# Only create service if it doesn't exist yet
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: auth-service
  annotations:
    helm.sh/resource-policy: keep
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  selector:
    app: auth-service
    color: {{ .Values.color }}
{{- end }}
