replicaCount: 1
appName: auth-service

image:
  repository: sujan1234ray/auth-service
  pullPolicy: IfNotPresent
  tag: "latest"

color: blue

service:
  type: LoadBalancer
  port: 80
  targetPort: 3001

serviceName: auth-service

# Environment variables for ConfigMap
env:
  CORS_ORIGINS: "http://localhost:4200,https://hamrorealstate.store,https://web.pokharelsujan.info.np/"
  PORT: "3001"
  HOST: "localhost"
  DB_MODE: "cloud"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "neondb"
  DB_SCHEMA: "REALSTATE"
  LOGIN: "LOGIN_TABLE"
  USER_PROFILE: "USER_PROFILE_TABLE"
  CLIENT_ID: "539011910849-qk1h6i9c5t9d0bn094jaa9q6rt2k7amu.apps.googleusercontent.com"
  REDIRECT_URI: "http://localhost:8000/oauth2callback"
  JWT_EXPIRATION: "10m"
  NODE_ENV: "production"  # Will be overridden by Jenkins

# Sensitive variables for Secret
secrets:
  JWT_SECRET: "<inject-from-jenkins>"
  DB_PASSWORD: "<inject-from-jenkins>"
  DATABASE_URL: "<inject-from-jenkins>"
  CLIENT_SECRET: "<inject-from-jenkins>"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /health
    port: 3001
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 3001
  initialDelaySeconds: 10
  periodSeconds: 5

imagePullSecrets:
  - name: docker-hub-credentials

nodeSelector:
  kubernetes.io/arch: arm64

tolerations: []
affinity: {}
