# ============================================================
# Oracle Cloud Always Free Tier Configuration - $0/month
# ============================================================

replicaCount: 1  # Keep at 1 for free tier

appName: auth-service
color: blue  # For blue-green deployment

image:
  repository: sujan1234ray/auth-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 80
  targetPort: 3001
  serviceName: auth-service
  
  # ⚠️ CRITICAL: OCI Load Balancer Configuration for Always Free Tier
  # DO NOT CHANGE flexShapeMin/Max from "10" or you'll be charged!
  ociLoadBalancerType: "lb"
  loadBalancerShape: "flexible"
  flexShapeMin: "10"   # FREE tier limit - DO NOT INCREASE
  flexShapeMax: "10"   # FREE tier limit - DO NOT INCREASE
  
  # Your OKE Service LB Subnet OCID
  loadBalancerSubnet1: "ocid1.subnet.oc1.ap-tokyo-1.aaaaaaaadrjobrpvosw2w4dgqf3si2fniobqyzyd5k3j3endhdhvbgozb62q"
  loadBalancerSubnet2: ""
  
  internal: "false"  # Public load balancer
  healthCheckPath: "/health"
  healthCheckPort: "3001"

# Environment variables for ConfigMap
env:
  CORS_ORIGINS: "http://localhost:4200,https://pokharelsujan.info.np"
  PORT: "3001"
  HOST: "0.0.0.0"
  DB_MODE: "cloud"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "neondb"
  DB_SCHEMA: "REALSTATE"
  LOGIN: "LOGIN_TABLE"
  USER_PROFILE: "USER_PROFILE_TABLE"
  CLIENT_ID: "539011910849-qk1h6i9c5t9d0bn094jaa9q6rt2k7amu.apps.googleusercontent.com"
  REDIRECT_URI: "http://localhost:8000/oauth2callback"
  JWT_EXPIRATION: "10m"
  NODE_ENV: "production"

# Sensitive variables - Jenkins will inject these
secrets:
  JWT_SECRET: ""
  DB_PASSWORD: ""
  DATABASE_URL: ""
  CLIENT_SECRET: ""
  FIREBASE_DATABASE_URL: ""

# Resource limits - Optimized for Always Free Tier (4 OCPU + 24GB RAM total)
resources:
  limits:
    cpu: 1000m      # 1 CPU core max per pod
    memory: 2Gi     # 2GB RAM max per pod
  requests:
    cpu: 250m       # 0.25 CPU minimum
    memory: 512Mi   # 512MB minimum

# Health probes - Relaxed timings for free tier
livenessProbe:
  httpGet:
    path: /health
    port: 3001
  initialDelaySeconds: 45  # Longer wait for ARM/free tier nodes
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /health
    port: 3001
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3
  successThreshold: 1

imagePullSecrets:
  - name: docker-hub-credentials

# ❌ REMOVED: nodeSelector arm64 (OKE handles node selection)
nodeSelector: {}

tolerations: []
affinity: {}
